auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("listing/<int:listing_id>", views.listing, name="listing"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("bid", views.bid, name="bid"),
    path("comment", views.comment, name="comment"),
    path("close", views.close, name="close"),
    path("category", views.category, name="category"),
    path("category/<int:category_id>", views.category, name="category")

]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.db import models


class User(AbstractUser):
    watchlist = models.ManyToManyField("AuctionListing", related_name="watchlist_user", null=True, blank=True)

    def __str__(self):
        return self.username


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True, blank=False)

    def __str__(self):
        return self.name


class AuctionListing(models.Model):
    status = models.BooleanField(default=True)
    title = models.CharField(max_length=100, blank=False)
    description = models.TextField(blank=False)
    image = models.URLField(blank=True)
    starting_price = models.DecimalField(max_digits=8, decimal_places=2, blank=False, validators=[MinValueValidator(0.01)])
    current_price = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0.01)])
    highest_bid = models.OneToOneField("Bid", related_name="highest_bid", on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    bidding_count = models.IntegerField(default=0)
    seller = models.ForeignKey(User, related_name="auction_listing", on_delete=models.CASCADE, blank=False)
    category = models.ForeignKey(Category, related_name="auction_listing", on_delete=models.SET_DEFAULT, default=1)

    def __str__(self):
        return self.title

    # Set current_price automaticly.
    def save(self, *args, **kwargs):
        if not self.pk:  # If it's a new instance
            self.current_price = self.starting_price
        super().save(*args, **kwargs)


class Bid(models.Model):
    amount = models.DecimalField(max_digits=8, decimal_places=2, blank=False, validators=[MinValueValidator(0.01)])
    auction_listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, blank=False)
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)

    def __str__(self):
        return f"Bid of {self.amount}$ on {self.auction_listing}"


class Comment(models.Model):
    text = models.TextField(blank=False)
    auction_listing = models.ForeignKey(AuctionListing, related_name="comments", on_delete=models.CASCADE, blank=False)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)

    def __str__(self):
        return self.text

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
from django.contrib.auth.decorators import login_required
from .helpers import *
from .models import *


def index(request):
    # Retrives all active listings.
    listings = AuctionListing.objects.filter(status=True)
    return render(request, "auctions/index.html", {
            "listings": listings,
    })


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
                })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request,
                "auctions/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


class CreateListingForm(forms.ModelForm):
    class Meta:
        model = AuctionListing
        fields = ["title", "description", "image", "starting_price", "category"]


def create_listing(request):
    """Create a new listing."""
    form = CreateListingForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        form.instance.seller = request.user
        form.save()
        return HttpResponseRedirect(reverse("index"))

    return render(request, "auctions/create_listing.html", {
            "categories": Category.objects.all(),
    })


@login_required(login_url="login")
def listing(request, listing_id):
    # Validate and retrieve listing objcet.
    listing = get_listing(request, listing_id)
    if not isinstance(listing, AuctionListing):
      return listing 

    # Check if the listing is in the user's watchlist.
    in_watchlist = request.user.watchlist.filter(pk=listing_id).exists()

    # Get comments associated with the listing.
    comments = Comment.objects.filter(auction_listing=listing)

    return render(request, "auctions/listing.html", {
        "listing": listing,
        "in_watchlist": in_watchlist,
        "comments": comments
    })


@login_required(login_url="login")
def watchlist(request):
    user = request.user

    if request.method == "POST":
        # Get listing id and validtade it.
        listing_id = get_listing_id(request)
        if not isinstance(listing_id, int):
            return listing_id

        # Get listing and validate it.
        listing = get_listing(request, listing_id)
        if not isinstance(listing, AuctionListing):
            return listing

        # Get action to add or remove listing form watchlist.
        action = request.POST.get("action")

        # Add or remove watch list or render error.
        if action == "add":
            user.watchlist.add(listing)
        elif action == "remove":
            user.watchlist.remove(listing)
        else:
            return render(request, "auctions/error.html", {
                 "message": f"Invalid action",
            })

        # Redirect back to the same listing page.
        return HttpResponseRedirect(reverse("listing", args=[listing_id]))

    # When the method is GET, display all active user listings.
    listings = user.watchlist.all() # Retrieve watchlist items.
    return render(request, "auctions/watchlist.html", {
        "listings": listings
    })


@login_required(login_url="login")
def bid(request):
    if request.method == "POST":
        user = request.user

        # Validate and retrieve the listing ID.
        listing_id = get_listing_id(request)
        if not isinstance(listing_id, int):
            return listing_id

        # Validate and retrieve the auction listing object.
        listing = get_listing(request, listing_id)
        if not isinstance(listing, AuctionListing):
            return listing

        # Validate and retrieve the bid amount.
        try:
            amount = float(request.POST.get("amount"))
            message = None
        except ValueError:
            message = "The amount should be a numebr!"

        # If an error message exists, render the error message.
        if message:
            return render(request, "auctions/error.html", {
                "message": message
            })

        # Ensure the bid amount is greater than the current price.
        if amount <= listing.current_price:
            return render(request, "auctions/error.html", {
                "message": f"The amount should be greater than ${listing.current_price}",
            })

        # Create a new bid.
        new_bid = Bid.objects.create(amount=amount, auction_listing=listing, bidder=user)

        # Update the current price and bidding count of the listing.
        listing.current_price = amount
        listing.bidding_count += 1
        listing.highest_bid = new_bid
        listing.save()

        # Redirect the user to the new listing page.
        return HttpResponseRedirect(reverse("listing", args=[listing_id]))

    # If request method is GET, render error paeg 
    return render(request, "auctions/error.html", {
        "message": "Use the form to place a bid."
    })


@login_required(login_url="login")
def comment(request):
    if request.method == "POST":
        user = request.user

        # Validate and retrieve comment text.
        text = str(request.POST.get("text"))
        if not text:
            return render(request, "auctions/error.html", {
                "message": "Your comment must have text content."
            })

        # Validate and retrieve listing ID.
        listing_id = get_listing_id(request)
        if not isinstance(listing_id, int):
            return listing_id

        # Validate and retrieve listing.
        listing = get_listing(request, listing_id, status=True)
        if not isinstance(listing, AuctionListing):
            return listing

        # Create a new comment object.
        Comment.objects.create(text=text, commenter=user, auction_listing=listing)

        # Redircet the user to the same lising page.
        return HttpResponseRedirect(reverse("listing", args=[listing_id]))

    # If request method is GET, render the error page.
    return render(request, "auctions/error.html", {
        "message": "Use form to place a comment."
    })


@login_required(login_url="login")
def close(request):
    if request.method == "POST":
        # Validate and retrieve the listing ID.
        listing_id = get_listing_id(request)
        if not isinstance(listing_id, int):
            return listing_id

        # Validate and retrieve the listing object.
        listing = get_listing(request, listing_id)
        if not isinstance(listing, AuctionListing):
            return listing

        # Validate if the user is the seller of this listing.
        listing_seller = listing.seller
        if request.user == listing_seller:
            listing.status = False

            # Remove the listing from any watchlist.
            listing.watchlist_user.clear()

            listing.save()

            # Redirect the user to home page.
            return HttpResponseRedirect(reverse("index"))

        return render(request, "auctions/error.html", {
                "message": "Only the seller of this listing can close it."
        })

    # If request method is GET, render the error page.
    return render(request, "auctions/error.html", {
        "message": "Use the form to close the listing."
    })


def category(request, category_id=None):
    # If category ID is provided in the URL.
    if category_id:
        # Validate and retrieve the category object.
        try:
            category = Category.objects.get(pk=category_id)
        except Category.DoesNotExist:
            return render(request, "auctions/error.html", {
                "message": f"There is no category with ID {category_id}."
            })

        # Retrieve all active auction listings in this category.
        listings = AuctionListing.objects.filter(
            category=category, 
            status=True,
        )

        # Render the category page with its listings.
        return render(request, "auctions/category.html", {
                "category": category,
                "listings": listings,
        })

    # If no category ID is provided, render the pgae with all categories.
    categories = Category.objects.all()
    return render(request, "auctions/categories.html", {
            "categories": categories,
    })

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block title %}
    Categories
{% endblock %}

{% block body %}
        <div class="row">
            <div class="col-md-6">
                <ul class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'category' category.pk %}">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {{ category }}
                            </li>
                        </a>
                    {% empty %}
                        <li>
                            There isn't any category.
                        </li>
                    {% endfor %}
                </ul>
        </div>
        </div>
{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block title %}
    {{ category|title }}
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        {% for listing in listings %}
            <div class="col-md-12">
                <div class="listing">
                        <div style="flex: 2">
                            <a href="{% url 'listing' listing.pk %}">
                                <h3>{{ listing }}</h3>
                            </a>
                            <p class="price">Price: ${{ listing.current_price }}</p>
                            <p style="color: rgb(61, 60, 60);">Created at: {{ listing.created_at }}</p>
                        </div>
                        {% if listing.image %}
                            <img src="{{ listing.image }}" alt="{{ listing }} Image">
                        {% endif %}
                </div>
            </div>
        {% empty %}
            <div class="col-md-12">
                <div class="listing">
                        <div style="flex: 2">
                            <h4>No listings at this category.</h4>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
  </div>
  
{% endblock %}

auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block title %}
    Cretae new listing
{% endblock %}

{% block body %}
    <form action="{% url 'create_listing' %}" method="post">
        {% csrf_token %}
        <div class="form-group input-group">
            <div class="input-group-prepend">
                <label for="id_title" class="input-group-text">Title:</label>
            </div>
            <input class="form-control" type="text" name="title" maxlength="100" required id="id_title">
        </div>
        
        <div class="form-group input-group">
            <div class="input-group-prepend">
                <label for="id_image" class="input-group-text">Image URL:</label>
            </div>
            <input  class="form-control" type="url" name="image" maxlength="400" id="id_image">
        </div>

        <div class="form-group input-group">
            <div class="input-group-prepend">
                <label for="id_starting_price" class="input-group-text">Starting price:</label>
            </div>
            <input style="max-width: 150px;" class="form-control" type="number" name="starting_price" min="0.01" step="0.01" required id="id_starting_price">
        </div>
    
        <div class="form-group input-group">
            <div class="input-group-prepend">
                <label for="id_category" class="input-group-text">Category</label>
            </div>
            <select style="max-width: 150px;" class="form-control" data-style="btn-primary" name="category" id="id_category">
                {% for category in categories %}
                    <option value="{{ category.pk }}">{{ category }}</option>
                {% endfor %}
            </select>            
        </div>

        <div class="form-group input-group">
            <div class="input-group-prepend">
                <label for="id_description" class="input-group-text">Description:</label>
            </div>
            <textarea class="form-control" name="description" cols="40" rows="10" required id="id_description"></textarea>
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Create Listing</button>
        </div>
    </form>
{% endblock %}

auctions/templates/auctions/error.html
{% extends "auctions/layout.html" %}

{% block title %}
    Error page
{% endblock %}

{% block body %}
    {% if message %}
        <p>{{ message }}</p>
    {% else %}
        <p>There isn't any error message!</p>
    {% endif %}
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block title %}
    Active listings
{% endblock %}

{% block body %}    
    <div class="container">
        <div class="row">
            {% for listing in listings %}
                <div class="col-md-12">
                    <div class="listing">
                            <div style="flex: 2">
                                <a href="{% url 'listing' listing.pk %}">
                                    <h3>{{ listing }}</h3>
                                </a>
                                <p class="price">${{ listing.current_price }}</p>
                                <p style="color: rgb(61, 60, 60);">{{ listing.description }}</p>
                            </div>
                            {% if listing.image %}
                                <img src="{{ listing.image }}" alt="{{ listing }} Image">
                            {% endif %}
                    </div>
                </div>
            {% empty %}
                <div class="col-md-12">
                    <div class="listing">
                            <div style="flex: 2">
                                <h4>No listings</h4>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
      </div>
      
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <title>{% block title %}Auctions{% endblock %}</title>
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_listing' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">Watch List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'category' %}">Categories</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block title %}
    {{ listing }}
{% endblock %}

{% block body %}
<main>
    {% if not listing.status %}
        {% if listing.highest_bid.bidder == user %}
            <p class="alert alert-success">Congratulations! You have won this auction.</p>
        {% else %}
            <p class="alert alert-danger">This listing has been closed!</p>
        {% endif %}
    {% endif %}
    
    <div class="row">
        {% if listing.image %}
            <div class="col-md-4">
                <div class="image">
                    <img class="img-fluid" src="{{ listing.image }}" alt="{{ listing.title }} image">
                </div>
            </div>
        {% endif %}
        <div class="col-md-8">
            <h3 class="title">Listing: {{ listing.title }}</h3>
            <p class="description">{{ listing.description }}</p>
            <p class="price">${{ listing.current_price }}</p>
            <Details>
                <ul class="list-unstyled">
                    <li><strong>Date created:</strong> {{ listing.created_at }}</li>
                    <li><strong>Listed by:</strong> {{ listing.seller }}</li>
                    <li><strong>Category:</strong> {{ listing.category }}</li>
                </ul>
            </Details>
        </div>
    </div>
    {% if listing.status %}
        {% if user == listing.seller %}
            <form action="{% url 'close' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="listing_id" value="{{ listing.pk }}">
                <button type="submit" class="btn btn-danger mt-3">Close</button>
            </form>
        {% else %}
            <form action="{% url 'watchlist' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="listing_id" value="{{ listing.pk }}">
                {% if in_watchlist %}
                    <button class="btn btn-danger mt-3" name="action" type="submit" value="remove">Remove from watch list</button>
                {% else %}
                    <button class="btn btn-secondary mt-3" name="action" type="submit" value="add">Add to watch list</button>
                {% endif %}
            </form>
            <hr>
            <p>
                {{ listing.bidding_count }} bid(s) so far.

                {% if listing.highest_bid.bidder == user %}
                    Your bid is the current bid.
                {% endif %}
            </p>
            <form action="{% url 'bid' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="number" name="amount" min="0.01" step="0.01" required placeholder="Bid">
                </div>
                <input type="hidden" name="listing_id" value="{{ listing.pk }}">
                <div class="form-group">
                    <button class="btn btn-primary mt-3" type="submit">Place Bid</button>
                </div>
            </form>
        {% endif %}
        <div class="mt-4">
            <h4>Comments</h4>
            <form action="{% url 'comment' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" name="text" required placeholder="Add your comment">
                </div>
                <input type="hidden" name="listing_id" value="{{ listing.pk }}">
                <button class="btn btn-primary" type="submit">Comment</button>
            </form>
            <br>
            
            {% for comment in comments %}
                <div class="media">
                    <div class="media-body">
                        <h5 class="mt-0">{{ comment.commenter|title }}</h5>
                        <p>{{ comment.text }}</p>
                    </div>
                </div>
            {% empty %}
                <div class="media">
                    <div class="media-body">
                        <h5 class="mt-0">No comments</h5>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
</main>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block title %}
    Watchlist
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        {% for listing in listings %}
            <div class="col-md-12">
                <div class="listing">
                        <div style="flex: 2">
                            <a href="{% url 'listing' listing.pk %}">
                                <h3>{{ listing }}</h3>
                            </a>
                            <p class="price">Price: ${{ listing.current_price }}</p>
                            <p style="color: rgb(61, 60, 60);">Created at: {{ listing.created_at }}</p>
                        </div>
                        {% if listing.image %}
                            <img src="{{ listing.image }}" alt="{{ listing }} Image">
                        {% endif %}
                </div>
            </div>
        {% empty %}
            <div class="col-md-12">
                <div class="listing">
                        <div style="flex: 2">
                            <h4>No listings</h4>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
  </div>
  
{% endblock %}